### ISSUE TITLE
KeychainWrapper.default.object(of: String.self, forKey: tokenKey) return nil

### ISSUE THREAD

**Issue by bohdan-protas** [puretears/KeychainWrapper#2]
`KeychainWrapper.default.object(of: String.self, forKey: tokenKey)` return nil always, before it I stored property using `KeychainWrapper.default.set("String Value", forKey: tokenKey)`

**Comment by paulfreeman** [comment]
This is because a String that is bare (not a property of an object) is not jsonDecodable. It would have been clearer if the function call 'object' was named 'jsonObject' as only jsonObjects can be retrieved using 'object' calls (any return value must be first jsonDecoded from 'Data'). 

However I think this is a feature rather than a bug.  Now that the api is being used by people then  it may be best fixed via documentation and a unit test clarifying the semantics, such as 
 
 ```
  func testInvalidReadStringAsJSONObject() {
    kcWrapper.set(stringValue, forKey: stringKey)
    let result = kcWrapper.object(of: String.self, forKey: stringKey)
    
    XCTAssertNil(result, "object call should not fetch a bare String type as a JSON object")
  }
```
